"""Opening book: pre-played board states the arena starts from.

A deterministic greedy-MCTS arena from the initial board reaches the same
game every time (only color alternation varies), so head-to-head results
collapse to win/lose binaries. Following Leela Chess Zero's opening-book
idea, the arena instead starts each pair of games from one book state:
net_a plays the side to move in game 1 and the other side in game 2, which
restores outcome diversity while keeping both nets symmetrically exposed.

File format (``model/openbook.json``, generated by tools/make_openbook.py):

- The JSON file holds a list of entries; each entry is a 5x5 array (rows
  indexed by board row x left-to-right top-to-bottom, columns by grid
  column z) of 5-char stack strings. Char k of a cell string is stack
  level y=k: 'w' = white piece, 'b' = black piece, '.' = empty, bottom to
  top. Example: ``"wbbb."`` = three black pieces stacked above one white
  piece.
- The player to move is NOT stored: it follows from piece counts
  (equal -> white to move, one more white -> black to move), which always
  holds for positions reachable from the initial board.

The loader is strict: any malformed entry raises ValueError naming the
entry index. A missing (or empty) JSON file simply yields an empty book
and the arena falls back to playing from the initial board.
"""

import json
from pathlib import Path

from .game import (
    BLACK,
    DEFAULT_PIECES,
    WHITE,
    GameState,
    _WIN_LINES,
)

BOOK_PATH = Path(__file__).resolve().parent.parent / "openbook.json"


def book_key(state: GameState) -> tuple:
    """Deduplication key: exact bitboards plus side to move (winner must be
    None for book states, so it is not part of the key)."""
    return (state.white, state.black, state.current)


def _popcount(x: int) -> int:
    return bin(x).count("1")


def state_to_entry(state: GameState) -> list:
    """Render a GameState as the 5x5 array-of-stack-strings book format."""
    if state.winner is not None:
        raise ValueError("book states must be non-terminal")
    grid = state.grid  # grid[x][z][y], values 0=white 1=black None
    entry = []
    for x in range(5):
        row = []
        for z in range(5):
            cell = ""
            for y in range(5):
                v = grid[x][z][y]
                cell += "." if v is None else ("w" if v == 0 else "b")
            row.append(cell)
        entry.append(row)
    return entry


def entry_to_state(entry, index: int | None = None) -> GameState:
    """Parse one book entry into a GameState. Strict: raises ValueError with
    the entry index on any malformation."""
    where = "" if index is None else f" (entry {index})"
    who = f"openbook{where}: "

    def fail(msg: str):
        raise ValueError(who + msg)

    if not isinstance(entry, (list, tuple)) or len(entry) != 5:
        fail(f"expected 5 rows, got {entry!r}")
    white = black = 0
    for x, row in enumerate(entry):
        if not isinstance(row, (list, tuple)) or len(row) != 5:
            fail(f"row {x} must be 5 columns, got {row!r}")
        for z, cell in enumerate(row):
            if not isinstance(cell, str) or len(cell) != 5:
                fail(f"cell ({x},{z}) must be a 5-char string, got {cell!r}")
            seen_gap = False
            for y, ch in enumerate(cell):
                if ch == ".":
                    seen_gap = True
                elif ch in ("w", "b"):
                    if seen_gap:
                        fail(
                            f"cell ({x},{z}) {cell!r} has a piece above an "
                            "empty level — floating pieces are unreachable"
                        )
                    bit = 1 << (x * 25 + z * 5 + y)
                    if ch == "w":
                        white |= bit
                    else:
                        black |= bit
                else:
                    fail(f"cell ({x},{z}) has invalid char {ch!r} ('w', 'b', '.')")

    nw, nb = _popcount(white), _popcount(black)
    if abs(nw - nb) > 1:
        fail(f"unbalanced material: {nw} white vs {nb} black pieces")
    if nw == nb:
        current = WHITE
    else:
        current = BLACK  # exactly one more white piece on the board
    if DEFAULT_PIECES - nw <= 0 or DEFAULT_PIECES - nb <= 0:
        fail("a player has no pieces left — terminal draw state")

    # No pre-existing win for either color: a won position is not playable.
    for _cells, mask in _WIN_LINES:
        if white & mask == mask:
            fail("white has already won — terminal state")
        if black & mask == mask:
            fail("black has already won — terminal state")

    return GameState(
        white=white,
        black=black,
        pieces_left={WHITE: DEFAULT_PIECES - nw, BLACK: DEFAULT_PIECES - nb},
        current=current,
        winner=None,
    )


def load_book() -> list:
    """Load ``model/openbook.json`` and parse every entry into GameStates.

    Raises ValueError on the first malformed or duplicated entry. A missing
    or empty file returns [] (arena falls back to the initial board).
    """
    try:
        entries = json.loads(BOOK_PATH.read_text())
    except FileNotFoundError:
        return []
    if not isinstance(entries, list):
        raise ValueError(f"openbook: {BOOK_PATH} must hold a list of entries")
    book = []
    seen = set()
    for i, entry in enumerate(entries):
        state = entry_to_state(entry, index=i)
        key = book_key(state)
        if key in seen:
            raise ValueError(f"openbook: duplicate entry {i}")
        seen.add(key)
        book.append(state)
    return book


def game_plans(book_len: int, games: int) -> list:
    """Per-game plan of (book_index, a_moves_first) for `games` arena games.

    Book states are taken in sequence, wrapping around after the last one,
    so a book of n states serves 2n contests: each state played twice with
    swapped roles (net_a to move vs net_b to move). Games come in pairs
    sharing one state; with an odd count the last state plays once. With no
    book (book_len == 0) the plan falls back to the classic alternating
    colors from the initial board.
    """
    if book_len <= 0:
        return [(None, i % 2 == 0) for i in range(games)]
    return [(i // 2 % book_len, i % 2 == 0) for i in range(games)]
